name: Deploy Infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'infrastructure/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Cloud Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: 'ai-content-generator-478607'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var="gcp_project_id=ai-content-generator-478607" -var="region=us-central1"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="gcp_project_id=ai-content-generator-478607" -var="region=us-central1"